### ISSUE TITLE
Peer to peer code review

### ISSUE THREAD

**Issue by OscarFMdev** [Alhajideen/Portfolio-setup#11]
## Issue description

I like how the design is looking, but there are some changes that we notice can improve your design:
- Header banner could be a little higher.
- You could add padding to the form section.
- The submit button from the form could be alinged to center.

### Happy coding! :medal_sports:

**Comment by ndorrh** [comment]
Great job so far with your project.
- I think the height of the background images should be adjusted for different screen sizes so that it matches the Figma template 
- I think you should Add some media queries for other screen sizes


Happy Coding
