### ISSUE TITLE
Portfolio: application deploy

### ISSUE THREAD

**Issue by Alhajideen** [Alhajideen/Portfolio-setup#13]
# Portfolio Online version
Since I have deployed my portfolio project earlier, I created this issue to show a link to the online version of my project.
Find below a link to my project as requested.

- Link : https://alhajideen.github.io/Portfolio-setup/

I anticipate your questions, suggestions and corrections 😄 .

**Comment by ghost** [comment]
Hi @Alhajideen , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![YesYouAreGIF (2)](https://user-images.githubusercontent.com/50941074/172881298-64e98170-87c5-4075-8a77-71d65d991f55.gif)
## Highlights

✅ Correct use of Github workflow
✅ No linter error
✅ README is okay

## Optional suggestions
- [OPTIONAL]  You can use this format `[name of the link](the actual link address)`  to make your readme more appealing as this will only display the name of the link and not the whole link address😄 .

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
